// Minimal extraction from a ClickOnce deployment manifest (<App>.application).
// The format is fixed enough (generated by Visual Studio/MSBuild) that a
// regex on the two interesting elements is sufficient and keeps us dependency free.

const VERSION_RE = /^\d+\.\d+\.\d+\.\d+$/;

function attr(tag, name) {
  const m = new RegExp(`\\s${name}="([^"]*)"`).exec(tag);
  return m ? m[1] : null;
}

export function parseDeploymentManifest(xml) {
  const text = xml.replace(/^﻿/, '');
  const idTag = /<assemblyIdentity\b[^>]*>/.exec(text);
  const providerTag = /<deploymentProvider\b[^>]*>/.exec(text);
  const name = idTag ? attr(idTag[0], 'name') : null;
  const version = idTag ? attr(idTag[0], 'version') : null;
  return {
    // e.g. "IQB-Kodieren.application"
    name,
    // e.g. "IQB-Kodieren"
    appName: name ? name.replace(/\.application$/i, '') : null,
    version: version && VERSION_RE.test(version) ? version : null,
    deploymentProvider: providerTag ? attr(providerTag[0], 'codebase') : null
  };
}
